language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - spec/gemfiles/Gemfile.rails-3.0.x
  - spec/gemfiles/Gemfile.rails-3.1.x
  - spec/gemfiles/Gemfile.rails-3.x